

;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega32-examples-button_example]
platform = atmelavr
board = ATmega32
;framework = arduino

; فقط لایبرری + مثال خاص
build_src_filter = +<../examples/button_example/> +<../src/> +<../lib/>

build_flags =
    -DF_CPU=8000000UL

[env:ATmega32-examples-DipSwitch-example]
platform = atmelavr
board = ATmega32
;framework = arduino

; فقط لایبرری + مثال خاص
build_src_filter = +<../examples/DipSwitch-example/> +<../src/> +<../lib/>

build_flags =
    -DF_CPU=8000000UL
   