

;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega32]
platform = atmelavr
board = ATmega32
;framework = arduino

; فقط فایل‌های لایبرری + این مثال خاص رو بیلد کن
build_src_filter = +<src/> +<examples/button_example/>

build_flags =
    -DF_CPU=8000000UL